# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 6
      - 7
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
nfpms:
  # note that this is an array of nfpm configs
  - # Your app's vendor.
    # Default is empty.
    vendor: Nicky Semenza
    # Your app's homepage.
    # Default is empty.
    homepage: https://github.com/nickysemenza/cm500_exporter

    # Your app's maintainer (probably you).
    # Default is empty.
    maintainer: Nicky Semenza <n@nickysemenza.com>

    # Your app's description.
    # Default is empty.
    description: Netgear CM500 Prometheus exporter

    # Formats to be generated.
    formats:
      - deb
      - rpm

    # Override default /usr/local/bin destination for binaries
    bindir: /usr/bin
